-- DATEDIFF(구분자(날짜의 경우 dd, day), 시작일, 종료일)
-- LIMIT: 오라클에서는 ROWNUM, MsSQL에서는 TOP과 같은 기능을 한다.
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS AS A, ANIMAL_OUTS AS B 
WHERE A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DATEDIFF(A.DATETIME, B.DATETIME) 
LIMIT 2